baseURL = "https://www.origamie.org"
languageCode = "fr-fr"
title = "Association Origamie - Production Musicale et Evénement Culturels"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[markup]
defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  description = "Origamie association"
  facebook = "https://www.facebook.com/origa1000"
  twitter = ""
  instagram = "https://www.instagram.com/origa1000/"
  youtube = "https://www.youtube.com/channel/UCM8oGyi_XvoMXYXnh9gYZWg?view_as=subscriber"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = ""
  site_logo = "/images/logotype_blanc_menu.png"
  site_logo_big = "images/origamie_logo_blanc.png"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]
  body_classes = "roboto bg-near-white"
  post_content_classes = "roboto"
  mainSections = ['news']

[related]
  threshold = 0
  includeNewer = true
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name  = "date"
    weight = 10

