baseURL = "http://www.origamie.org"
languageCode = "fr-fr"
title = "Origamie"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  description = "Origamie association"
  facebook = "https://www.facebook.com/origa1000"
  twitter = ""
  instagram = "https://www.instagram.com/origa1000/"
  youtube = "https://www.youtube.com/channel/UCM8oGyi_XvoMXYXnh9gYZWg?view_as=subscriber"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/origamie_full.jpg"
  recent_posts_number = 2
